#!/usr/bin/env bash

APT="/usr/bin/apt"

case "$1" in
  "" )
    sudo bash /usr/bin/pardus-helper
    ;;

  --about )
    echo
    echo "Pardus Package Manager"
    echo "Basit Komutlar:"
    echo "install - İstediğiniz paketi indirir"
    echo "remove - İstediğiniz paketi siler"
    echo "update - Güncelleme yapar"
    echo "upgrade - Paket versionlarını artırır"
    echo
    exit 0
    ;;

  --version )
    echo
    echo "Versiyon 1.0"
    echo
    exit 0
    ;;

  # Commands that DO NOT require sudo
  search|show|list )
    sudo bash "$APT" "$@"
    ;;

  # Commands that DO require sudo
  install|remove|purge|update|upgrade|full-upgrade|autoremove )
    sudo bash "$APT" "$@"
    ;;

  * )
    sudo bash "$APT" "$@"
    ;;
esac
